public class arithmaticCalculations {
    public void addition(integer x, integer y) {
        Integer z = x + y;
        system.debug('The sum of these two variables is: ' + z);
    }

    public void subtraction(integer x, integer y){
        Integer z = x - y;
        system.debug('Subtraction of these two variables is: ' + z);
    }

    public void multiplication(integer x, integer y, integer m){
        integer z = x * y * m;
        system.debug('The multiplication of these three variables is: ' + z);

    }
}
