/* public with sharing class CarCall {
    public void callCars() {
        Car objectName = new Car();
        objectName.function();
        objectName.sum();

        string firstVariable = 'test';
        integer aaa = 7;
        string bbb = '7';

    }
}
*/

   /* string firstName = 'Dila';
    string lastName = 'Akhmedova';
    string fullName = firstName + ' ' + lastName;
    system.debug('Full Name: ' + fulllName);
*/

String sessionDescr = 'jhgjhghgjggjhg';
integer size = sessionDescr.length();
boolean 


